{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    kdePackages.kate
    kdePackages.gwenview
    kdePackages.ark
    kdePackages.kdf
    kdePackages.kup
    kdePackages.kalk
    kdePackages.kded
    kdePackages.kget
    kdePackages.kgpg
    kdePackages.kmag
    kdePackages.kmix
    kdePackages.koko
    kdePackages.kolf
    kdePackages.kpat
    kdePackages.krdc
    kdePackages.krdp
    kdePackages.krfb
    kdePackages.ksvg
    kdePackages.kwin
    kdePackages.audex
    kdePackages.elisa
    kdePackages.kasts
    kdePackages.kauth
    kdePackages.kcalc
    kdePackages.kcron
    kdePackages.kfind
    kdePackages.kmail
    kdePackages.kwave
    kdePackages.timed
    kdePackages.breeze
    kdePackages.dragon
    kdePackages.falkon
    kdePackages.kalarm
    kdePackages.kapman
    kdePackages.kcrash
    kdePackages.kgamma
    kdePackages.kmines
    kdePackages.kruler
    kdePackages.ktimer
    kdePackages.kzones
    kdePackages.oxygen
    kdePackages.taglib
    kdePackages.dolphin
    kdePackages.drkonqi
    kdePackages.kbackup
    kdePackages.kblocks
    kdePackages.kbounce
    kdePackages.kcodecs
    kdePackages.kconfig
    kdePackages.kdialog
    kdePackages.knights
    kdePackages.kompare
    kdePackages.konsole
    kdePackages.kontact
    kdePackages.kpeople
    kdePackages.kpmcore
    kdePackages.krunner
    kdePackages.kscreen
    kdePackages.kwallet
    kdePackages.kwrited
    kdePackages.discover
    kdePackages.karchive
    kdePackages.khangman
    kdePackages.kpackage
    kdePackages.kservice
    kdePackages.ktorrent
    kdePackages.oxygen-icons
    kdePackages.oxygen-sounds
  ];
}
